### ISSUE TITLE
License appears to be AGPL-3.0 with changes, this violates the copyright of Free Software Foundation, Inc. 

### ISSUE THREAD

**Issue by mr-c** [AMCeScience/Rosemary-Vanilla#8]
See https://www.gnu.org/licenses/agpl-3.0.html

> Copyright © 2007 Free Software Foundation, Inc. <http://fsf.org/> 
> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.
>

**Comment by mr-c** [comment]
Suggestion: restore the full text of the AGPL-3.0 or choose another license :-)

**Comment by SilviaOlabarriaga** [comment]
hi Marco,

thanks for the note. 
we had extensive discussions with lawyers and all about how to formulate our intention to keep the software free for non-commercial use. 
we do not mention AGPL-3.0 on purpose, because this would not be allowed.
i guess our advisors overlooked this copyright term you now so clearly expose.

we will sort out this asap.

**Comment by MrMojoRisin71** [comment]
Hi, I am the one who drafted this license. I did not overlook that sentence, but GNU (and FSF) is somewhat ambiguous in this sense. In its FAQ (https://www.gnu.org/licenses/gpl-faq.html#ModifyGPL), it explicitly allows for modifications of its license under certain conditions:

> **Can I modify the GPL and make a modified license? (#ModifyGPL)**
> It is possible to make modified versions of the GPL, but it tends to have practical consequences.
> You can legally use the GPL terms (possibly modified) in another license provided that you call your license by another name and do not include the GPL preamble, and provided you modify the instructions-for-use at the end enough to make it clearly different in wording and not mention GNU (though the actual procedure you describe may be similar).
> If you want to use our preamble in a modified license, please write to licensing@gnu.org for permission. For this purpose we would want to check the actual license requirements to see if we approve of them.
> Although we will not raise legal objections to your making a modified license in this way, we hope you will think twice and not do it. Such a modified license is almost certainly incompatible with the GNU GPL, and that incompatibility blocks useful combinations of modules. The mere proliferation of different free software licenses is a burden in and of itself.
> Rather than modifying the GPL, please use the exception mechanism offered by GPL version 3. 

On that basis, we removed references to GPL and GNU and complied with the other requirements, not to infringe the copyright in the license.

**Comment by SilviaOlabarriaga** [comment]
Thanks for the clarification, happy to hear that all our effort to do things right was worthwhile.
As this is sorted out now, we keep the text as it is.

**Comment by mr-c** [comment]
![agpl3](https://cloud.githubusercontent.com/assets/1330696/20133085/f41eb6d6-a65d-11e6-96e0-0fe6b5fbeecb.png)

FYI, GitHub displays this project as being AGPL-3.0. Perhaps you did not "make it clearly different in wording"?

**Comment by shayanlinux** [comment]
The modifications applied to AGPLv3 to make Rosemary license are:
-  addition of item "a" in section 5
-  deletion of section 14

The icon added automatically by Github is indeed incorrect.

**Comment by mr-c** [comment]
@shayanlinux Thank you for clarifying the changes to the original license. This makes the project non-free and non-open source as your license prohibits the distribution of derivative works for commercial purposes: see "3. Derived Works" https://opensource.org/osd
